//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case_Study.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitkiler
    {
        public int Id { get; set; }
        public string BitkiAdi { get; set; }
        public string BitkiAciklamasi { get; set; }
        public string BitkiFaydasi { get; set; }
        public string BitkiResmi { get; set; }
    }
}
